import { pictures } from "../assets";
export const data = {
  dataMenu: ["home", "featured", "women", "new", "products"],

  dataProduct: [
    {
      productId: 1,
      productName: "Nike Jordan",
      productPrice: 149.99,
      productImage: pictures.featured1,
      productBrands: "Nike",
      productCatalog: "featured",
    },
    {
      productId: 2,
      productName: "Nike Free RN",
      productPrice: 149.99,
      productImage: pictures.featured2,
      productBrands: "Nike",
      productCatalog: "featured",
    },
    {
      productId: 3,
      productName: "Nike Free RN",
      productPrice: 149.99,
      productImage: pictures.featured3,
      productBrands: "Nike",
      productCatalog: "featured",
    },
    {
      productId: 4,
      productName: "Nike Jordan",
      productPrice: 149.99,
      productImage: pictures.featured1,
      productBrands: "Nike",
      productCatalog: "featured",
    },
    {
      productId: 5,
      productName: "Nike Jordan",
      productPrice: 149.99,
      productImage: pictures.featured1,
      productBrands: "Nike",
      productCatalog: "featured",
    },
    {
      productId: 6,
      productName: "Nike Free RN",
      productPrice: 149.99,
      productImage: pictures.featured2,
      productBrands: "Nike",
      productCatalog: "featured",
    },
    {
      productId: 7,
      productName: "Nike Free RN",
      productPrice: 149.99,
      productImage: pictures.featured3,
      productBrands: "Nike",
      productCatalog: "featured",
    },
    {
      productId: 8,
      productName: "Nike Jordan",
      productPrice: 149.99,
      productImage: pictures.featured1,
      productBrands: "Nike",
      productCatalog: "featured",
    },
    {
      productId: 9,
      productName: "Nike Free TR",
      productPrice: 129.99,
      productImage: pictures.women1,
      productBrands: "Nike",
      productCatalog: "women",
    },
    {
      productId: 10,
      productName: "Nike Free TR",
      productPrice: 129.99,
      productImage: pictures.women2,
      productBrands: "Nike",
      productCatalog: "women",
    },
    {
      productId: 11,
      productName: "Nike Free TR",
      productPrice: 129.99,
      productImage: pictures.women3,
      productBrands: "Nike",
      productCatalog: "women",
    },
    {
      productId: 12,
      productName: "Nike Free TR",
      productPrice: 129.99,
      productImage: pictures.women4,
      productBrands: "Nike",
      productCatalog: "women",
    },
    {
      productId: 13,
      productName: "Men Shoes",
      productPrice: 129.99,
      productImage: pictures.new1,
      productBrands: "Nike",
      productCatalog: "new",
    },
    {
      productId: 14,
      productName: "Nike Free TR",
      productPrice: 129.99,
      productImage: pictures.new2,
      productBrands: "Nike",
      productCatalog: "new",
    },
    {
      productId: 15,
      productName: "Nike Free TR",
      productPrice: 129.99,
      productImage: pictures.new3,
      productBrands: "Nike",
      productCatalog: "new",
    },
    {
      productId: 16,
      productName: "Nike Free TR",
      productPrice: 129.99,
      productImage: pictures.new4,
      productBrands: "Nike",
      productCatalog: "new",
    },
    {
      productId: 17,
      productName: "Nike Free TR",
      productPrice: 129.99,
      productImage: pictures.new5,
      productBrands: "Nike",
      productCatalog: "new",
    },
    {
      productId: 18,
      productName: "Nike Free TR",
      productPrice: 129.99,
      productImage: pictures.new2,
      productBrands: "Nike",
      productCatalog: "new",
    },
    {
      productId: 19,
      productName: "Nike Free TR",
      productPrice: 129.99,
      productImage: pictures.new3,
      productBrands: "Nike",
      productCatalog: "new",
    },
    {
      productId: 20,
      productName: "Nike Free TR",
      productPrice: 129.99,
      productImage: pictures.new4,
      productBrands: "Nike",
      productCatalog: "new",
    },
    {
      productId: 21,
      productName: "Nike Free TR",
      productPrice: 129.99,
      productImage: pictures.new5,
      productBrands: "Nike",
      productCatalog: "new",
    },
    {
      productId: 22,
      productName: "Nike Free TR",
      productPrice: 129.99,
      productImage: pictures.women1,
      productBrands: "Nike",
      productCatalog: "women",
    },
    {
      productId: 23,
      productName: "Nike Free TR",
      productPrice: 129.99,
      productImage: pictures.women2,
      productBrands: "Nike",
      productCatalog: "women",
    },
    {
      productId: 24,
      productName: "Nike Free TR",
      productPrice: 129.99,
      productImage: pictures.women3,
      productBrands: "Nike",
      productCatalog: "women",
    },
    {
      productId: 25,
      productName: "Nike Free TR",
      productPrice: 129.99,
      productImage: pictures.women4,
      productBrands: "Nike",
      productCatalog: "women",
    },
  ],

  dataConnection: [
    {
      connectionId: 4,
      connectionName: "Nike",
      connectionImage: pictures.collection1,
      brands: "Nike",
    },
    {
      connectionId: 5,
      connectionName: "Addidas",
      connectionImage: pictures.collection2,
      brands: "Addidas",
    },
  ],

  dataOffer: {
    offerId: 10,
    offerTitle: "50% OFF",
    offerDescription: "In Adidas Superstar sneakers",
    offerImage: pictures.offert,
  },

  dataPeople: [
    {
      peopleId: 1,
      peopleImage:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1595959131/person-2_ipcjws.jpg",
      peopleName: "maria ferguson",
      peopleTitle: "office manager",
      peopleQuote:
        "Fingerstache umami squid, kinfolk subway tile selvage tumblr man braid viral kombucha gentrify fanny pack raclette pok pok mustache.",
    },
    {
      peopleId: 2,
      peopleImage:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1586883417/person-3_ipa0mj.jpg",
      peopleName: "john doe",
      peopleTitle: "regular guy",
      peopleQuote:
        "Gastropub sustainable tousled prism occupy. Viral XOXO roof party brunch actually, chambray listicle microdosing put a bird on it paleo subway tile squid umami.",
    },
    {
      peopleId: 3,
      peopleImage:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1595959121/person-1_aufeoq.jpg",
      peopleName: "peter smith",
      peopleTitle: "product designer",
      peopleQuote:
        "Drinking vinegar polaroid street art echo park, actually semiotics next level butcher master cleanse hammock flexitarian ethical paleo.",
    },
    {
      peopleId: 4,
      peopleImage:
        "https://res.cloudinary.com/diqqf3eq2/image/upload/v1586883334/person-1_rfzshl.jpg",
      peopleName: "susan andersen",
      peopleTitle: "the boss",
      peopleQuote:
        "Marfa af yr 3 wolf moon kogi, readymade distillery asymmetrical seitan kale chips fingerstache cloud bread mustache twee messenger bag. ",
    },
  ],
};
